spring.application.name=picasyfijas

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d81u4ae7r5hc73dv3n8g-a.oregon-postgres.render.com:5432/picasyfijas_db_4nqo
spring.datasource.username=picasyfijas_db_4nqo_user
spring.datasource.password=yXTZ8cTenRGTka1ZAJkqxc2S9x9Q8Vum
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true